package com.chungli.mapper;

import com.chungli.dto.Brokerage;
import com.chungli.dto.BrokerageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrokerageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int countByExample(BrokerageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByExample(BrokerageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByPrimaryKey(Integer BrokId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insert(Brokerage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insertSelective(Brokerage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	List<Brokerage> selectByExample(BrokerageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	Brokerage selectByPrimaryKey(Integer BrokId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Brokerage record,
			@Param("example") BrokerageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExample(@Param("record") Brokerage record,
			@Param("example") BrokerageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKeySelective(Brokerage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Brokerage
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKey(Brokerage record);
}