package com.chungli.mapper;

import com.chungli.dto.EaProgram;
import com.chungli.dto.EaProgramExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EaProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int countByExample(EaProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByExample(EaProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByPrimaryKey(Integer eaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insert(EaProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insertSelective(EaProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    List<EaProgram> selectByExample(EaProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    EaProgram selectByPrimaryKey(Integer eaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") EaProgram record, @Param("example") EaProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExample(@Param("record") EaProgram record, @Param("example") EaProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKeySelective(EaProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EaProgram
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKey(EaProgram record);
}