package com.chungli.mapper;

import com.chungli.dto.Team;
import com.chungli.dto.TeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int countByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByPrimaryKey(Integer teamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insert(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insertSelective(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	List<Team> selectByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	Team selectByPrimaryKey(Integer teamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Team record,
			@Param("example") TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExample(@Param("record") Team record,
			@Param("example") TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKeySelective(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Team
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKey(Team record);
}