package com.chungli.mapper;

import com.chungli.dto.UserProfile;
import com.chungli.dto.UserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProfileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int countByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int deleteByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int deleteByPrimaryKey(String email);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int insert(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int insertSelective(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	List<UserProfile> selectByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	UserProfile selectByPrimaryKey(String email);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserProfile record,
			@Param("example") UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int updateByExample(@Param("record") UserProfile record,
			@Param("example") UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int updateByPrimaryKeySelective(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserProfile
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	int updateByPrimaryKey(UserProfile record);
}