package com.chungli.mapper;

import com.chungli.dto.UserRefence;
import com.chungli.dto.UserRefenceExample;
import com.chungli.dto.UserRefenceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRefenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int countByExample(UserRefenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByExample(UserRefenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int deleteByPrimaryKey(UserRefenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insert(UserRefence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int insertSelective(UserRefence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	List<UserRefence> selectByExample(UserRefenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	UserRefence selectByPrimaryKey(UserRefenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserRefence record,
			@Param("example") UserRefenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByExample(@Param("record") UserRefence record,
			@Param("example") UserRefenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKeySelective(UserRefence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRefence
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	int updateByPrimaryKey(UserRefence record);
}