package com.chungli.mapper;

import com.chungli.dto.UserLive;
import com.chungli.dto.UserLiveExample;
import com.chungli.dto.UserLiveKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int countByExample(UserLiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByExample(UserLiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByPrimaryKey(UserLiveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insert(UserLive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insertSelective(UserLive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    List<UserLive> selectByExample(UserLiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    UserLive selectByPrimaryKey(UserLiveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserLive record, @Param("example") UserLiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExample(@Param("record") UserLive record, @Param("example") UserLiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKeySelective(UserLive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserLive
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKey(UserLive record);
}