package com.chungli.mapper;

import com.chungli.dto.UserPay;
import com.chungli.dto.UserPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int countByExample(UserPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByExample(UserPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int deleteByPrimaryKey(String userPayID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insert(UserPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int insertSelective(UserPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    List<UserPay> selectByExample(UserPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    UserPay selectByPrimaryKey(String userPayID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPay record, @Param("example") UserPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByExample(@Param("record") UserPay record, @Param("example") UserPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKeySelective(UserPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPay
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    int updateByPrimaryKey(UserPay record);
}