package com.chungli.dto;

import java.util.Date;

public class Brokerage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Integer BrokId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.BrokName
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String brokName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Date dateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Brokerage.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String userStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.BrokId
	 * @return  the value of Brokerage.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Integer getBrokId() {
		return BrokId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.BrokId
	 * @param BrokId  the value for Brokerage.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setBrokId(Integer BrokId) {
		this.BrokId = BrokId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.BrokName
	 * @return  the value of Brokerage.BrokName
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getBrokName() {
		return brokName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.BrokName
	 * @param brokName  the value for Brokerage.BrokName
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setBrokName(String brokName) {
		this.brokName = brokName == null ? null : brokName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.CrDate
	 * @return  the value of Brokerage.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.CrDate
	 * @param crDate  the value for Brokerage.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.CrUser
	 * @return  the value of Brokerage.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.CrUser
	 * @param crUser  the value for Brokerage.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.DateStamp
	 * @return  the value of Brokerage.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Date getDateStamp() {
		return dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.DateStamp
	 * @param dateStamp  the value for Brokerage.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setDateStamp(Date dateStamp) {
		this.dateStamp = dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Brokerage.UserStamp
	 * @return  the value of Brokerage.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getUserStamp() {
		return userStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Brokerage.UserStamp
	 * @param userStamp  the value for Brokerage.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setUserStamp(String userStamp) {
		this.userStamp = userStamp == null ? null : userStamp.trim();
	}
}