package com.chungli.dto;

public class DownloadHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.Email
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.UserLiveId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String userLiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.EaId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private Integer eaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.StartTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.EndTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.Email
     *
     * @return the value of DownloadHistory.Email
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.Email
     *
     * @param email the value for DownloadHistory.Email
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.UserLiveId
     *
     * @return the value of DownloadHistory.UserLiveId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getUserLiveId() {
        return userLiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.UserLiveId
     *
     * @param userLiveId the value for DownloadHistory.UserLiveId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setUserLiveId(String userLiveId) {
        this.userLiveId = userLiveId == null ? null : userLiveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.EaId
     *
     * @return the value of DownloadHistory.EaId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public Integer getEaId() {
        return eaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.EaId
     *
     * @param eaId the value for DownloadHistory.EaId
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setEaId(Integer eaId) {
        this.eaId = eaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.StartTime
     *
     * @return the value of DownloadHistory.StartTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.StartTime
     *
     * @param startTime the value for DownloadHistory.StartTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.EndTime
     *
     * @return the value of DownloadHistory.EndTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.EndTime
     *
     * @param endTime the value for DownloadHistory.EndTime
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }
}