package com.chungli.dto;

import java.util.Date;

public class DownloadHistory extends DownloadHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.CrDate
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private Date crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.CrUser
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.DateStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private Date dateStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DownloadHistory.UserStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    private String userStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.CrDate
     *
     * @return the value of DownloadHistory.CrDate
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.CrDate
     *
     * @param crDate the value for DownloadHistory.CrDate
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.CrUser
     *
     * @return the value of DownloadHistory.CrUser
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.CrUser
     *
     * @param crUser the value for DownloadHistory.CrUser
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.DateStamp
     *
     * @return the value of DownloadHistory.DateStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public Date getDateStamp() {
        return dateStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.DateStamp
     *
     * @param dateStamp the value for DownloadHistory.DateStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setDateStamp(Date dateStamp) {
        this.dateStamp = dateStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DownloadHistory.UserStamp
     *
     * @return the value of DownloadHistory.UserStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public String getUserStamp() {
        return userStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DownloadHistory.UserStamp
     *
     * @param userStamp the value for DownloadHistory.UserStamp
     *
     * @mbggenerated Sun May 08 19:27:55 CST 2016
     */
    public void setUserStamp(String userStamp) {
        this.userStamp = userStamp == null ? null : userStamp.trim();
    }
}