package com.chungli.dto;

import java.util.Date;

public class EaProgram {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.EaId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer eaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.EaName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String eaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer eaPayAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date dateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EaProgram.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.EaId
	 * @return  the value of EaProgram.EaId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getEaId() {
		return eaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.EaId
	 * @param eaId  the value for EaProgram.EaId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEaId(Integer eaId) {
		this.eaId = eaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.EaName
	 * @return  the value of EaProgram.EaName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getEaName() {
		return eaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.EaName
	 * @param eaName  the value for EaProgram.EaName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEaName(String eaName) {
		this.eaName = eaName == null ? null : eaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.EaPayAmount
	 * @return  the value of EaProgram.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getEaPayAmount() {
		return eaPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.EaPayAmount
	 * @param eaPayAmount  the value for EaProgram.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEaPayAmount(Integer eaPayAmount) {
		this.eaPayAmount = eaPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.CrDate
	 * @return  the value of EaProgram.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.CrDate
	 * @param crDate  the value for EaProgram.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.CrUser
	 * @return  the value of EaProgram.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.CrUser
	 * @param crUser  the value for EaProgram.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.DateStamp
	 * @return  the value of EaProgram.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getDateStamp() {
		return dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.DateStamp
	 * @param dateStamp  the value for EaProgram.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setDateStamp(Date dateStamp) {
		this.dateStamp = dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EaProgram.UserStamp
	 * @return  the value of EaProgram.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserStamp() {
		return userStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EaProgram.UserStamp
	 * @param userStamp  the value for EaProgram.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserStamp(String userStamp) {
		this.userStamp = userStamp == null ? null : userStamp.trim();
	}
}