package com.chungli.dto;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.RoleId
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.RoleName
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.CrDate
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private Date crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.CrUser
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.DateStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private Date dateStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.UserStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    private String userStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.RoleId
     *
     * @return the value of Role.RoleId
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.RoleId
     *
     * @param roleId the value for Role.RoleId
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.RoleName
     *
     * @return the value of Role.RoleName
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.RoleName
     *
     * @param roleName the value for Role.RoleName
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.CrDate
     *
     * @return the value of Role.CrDate
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.CrDate
     *
     * @param crDate the value for Role.CrDate
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.CrUser
     *
     * @return the value of Role.CrUser
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.CrUser
     *
     * @param crUser the value for Role.CrUser
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.DateStamp
     *
     * @return the value of Role.DateStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public Date getDateStamp() {
        return dateStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.DateStamp
     *
     * @param dateStamp the value for Role.DateStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setDateStamp(Date dateStamp) {
        this.dateStamp = dateStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.UserStamp
     *
     * @return the value of Role.UserStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public String getUserStamp() {
        return userStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.UserStamp
     *
     * @param userStamp the value for Role.UserStamp
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setUserStamp(String userStamp) {
        this.userStamp = userStamp == null ? null : userStamp.trim();
    }
}