package com.chungli.dto;

import java.util.Date;

public class UserLive extends UserLiveKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.EaId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Integer eaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Integer brokId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.Count
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.Status
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Integer Status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private Date dateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String userStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.EaId
	 * @return  the value of UserLive.EaId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Integer getEaId() {
		return eaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.EaId
	 * @param eaId  the value for UserLive.EaId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setEaId(Integer eaId) {
		this.eaId = eaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.BrokId
	 * @return  the value of UserLive.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Integer getBrokId() {
		return brokId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.BrokId
	 * @param brokId  the value for UserLive.BrokId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setBrokId(Integer brokId) {
		this.brokId = brokId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.Count
	 * @return  the value of UserLive.Count
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.Count
	 * @param count  the value for UserLive.Count
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.Status
	 * @return  the value of UserLive.Status
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Integer getStatus() {
		return Status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.Status
	 * @param Status  the value for UserLive.Status
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setStatus(Integer Status) {
		this.Status = Status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.CrDate
	 * @return  the value of UserLive.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.CrDate
	 * @param crDate  the value for UserLive.CrDate
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.CrUser
	 * @return  the value of UserLive.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.CrUser
	 * @param crUser  the value for UserLive.CrUser
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.DateStamp
	 * @return  the value of UserLive.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public Date getDateStamp() {
		return dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.DateStamp
	 * @param dateStamp  the value for UserLive.DateStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setDateStamp(Date dateStamp) {
		this.dateStamp = dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.UserStamp
	 * @return  the value of UserLive.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getUserStamp() {
		return userStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.UserStamp
	 * @param userStamp  the value for UserLive.UserStamp
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setUserStamp(String userStamp) {
		this.userStamp = userStamp == null ? null : userStamp.trim();
	}
}