package com.chungli.dto;

public class UserRefenceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserRefence.UserId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserRefence.ReferrerId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	private String referrerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserRefence.UserId
	 * @return  the value of UserRefence.UserId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserRefence.UserId
	 * @param userId  the value for UserRefence.UserId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserRefence.ReferrerId
	 * @return  the value of UserRefence.ReferrerId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public String getReferrerId() {
		return referrerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserRefence.ReferrerId
	 * @param referrerId  the value for UserRefence.ReferrerId
	 * @mbggenerated  Mon Feb 29 10:59:27 CST 2016
	 */
	public void setReferrerId(String referrerId) {
		this.referrerId = referrerId == null ? null : referrerId.trim();
	}
}