package com.chungli.dto;

import java.util.Date;

public class UserProfile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.Email
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.ChineseName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String chineseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.Password
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.Phone
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.Team
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer team;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date dateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.EnglishName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String englishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.LeaderEmail
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String leaderEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserProfile.RoleId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.Email
	 * @return  the value of UserProfile.Email
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.Email
	 * @param email  the value for UserProfile.Email
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.ChineseName
	 * @return  the value of UserProfile.ChineseName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.ChineseName
	 * @param chineseName  the value for UserProfile.ChineseName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName == null ? null : chineseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.Password
	 * @return  the value of UserProfile.Password
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.Password
	 * @param password  the value for UserProfile.Password
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.Phone
	 * @return  the value of UserProfile.Phone
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.Phone
	 * @param phone  the value for UserProfile.Phone
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.Team
	 * @return  the value of UserProfile.Team
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getTeam() {
		return team;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.Team
	 * @param team  the value for UserProfile.Team
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setTeam(Integer team) {
		this.team = team;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.CrDate
	 * @return  the value of UserProfile.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.CrDate
	 * @param crDate  the value for UserProfile.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.CrUser
	 * @return  the value of UserProfile.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.CrUser
	 * @param crUser  the value for UserProfile.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.DateStamp
	 * @return  the value of UserProfile.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getDateStamp() {
		return dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.DateStamp
	 * @param dateStamp  the value for UserProfile.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setDateStamp(Date dateStamp) {
		this.dateStamp = dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.UserStamp
	 * @return  the value of UserProfile.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserStamp() {
		return userStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.UserStamp
	 * @param userStamp  the value for UserProfile.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserStamp(String userStamp) {
		this.userStamp = userStamp == null ? null : userStamp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.EnglishName
	 * @return  the value of UserProfile.EnglishName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.EnglishName
	 * @param englishName  the value for UserProfile.EnglishName
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName == null ? null : englishName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.LeaderEmail
	 * @return  the value of UserProfile.LeaderEmail
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getLeaderEmail() {
		return leaderEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.LeaderEmail
	 * @param leaderEmail  the value for UserProfile.LeaderEmail
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setLeaderEmail(String leaderEmail) {
		this.leaderEmail = leaderEmail == null ? null : leaderEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserProfile.RoleId
	 * @return  the value of UserProfile.RoleId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserProfile.RoleId
	 * @param roleId  the value for UserProfile.RoleId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}