package com.chungli.dto;

public class UserLiveKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.UserLiveId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userLiveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserLive.BrokId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer brokId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.UserId
	 * @return  the value of UserLive.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.UserId
	 * @param userId  the value for UserLive.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.UserLiveId
	 * @return  the value of UserLive.UserLiveId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserLiveId() {
		return userLiveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.UserLiveId
	 * @param userLiveId  the value for UserLive.UserLiveId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserLiveId(String userLiveId) {
		this.userLiveId = userLiveId == null ? null : userLiveId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserLive.BrokId
	 * @return  the value of UserLive.BrokId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getBrokId() {
		return brokId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserLive.BrokId
	 * @param brokId  the value for UserLive.BrokId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setBrokId(Integer brokId) {
		this.brokId = brokId;
	}
}