package com.chungli.dto;

import java.util.Date;

public class UserPay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.InvoiceNumber
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String invoiceNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.EaID
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String eaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Integer eaPayAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.StartTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.EndTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private Date dateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserPay.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	private String userStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.InvoiceNumber
	 * @return  the value of UserPay.InvoiceNumber
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getInvoiceNumber() {
		return invoiceNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.InvoiceNumber
	 * @param invoiceNumber  the value for UserPay.InvoiceNumber
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber == null ? null : invoiceNumber
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.UserId
	 * @return  the value of UserPay.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.UserId
	 * @param userId  the value for UserPay.UserId
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.EaID
	 * @return  the value of UserPay.EaID
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getEaId() {
		return eaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.EaID
	 * @param eaId  the value for UserPay.EaID
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEaId(String eaId) {
		this.eaId = eaId == null ? null : eaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.EaPayAmount
	 * @return  the value of UserPay.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Integer getEaPayAmount() {
		return eaPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.EaPayAmount
	 * @param eaPayAmount  the value for UserPay.EaPayAmount
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEaPayAmount(Integer eaPayAmount) {
		this.eaPayAmount = eaPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.StartTime
	 * @return  the value of UserPay.StartTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.StartTime
	 * @param startTime  the value for UserPay.StartTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime == null ? null : startTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.EndTime
	 * @return  the value of UserPay.EndTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.EndTime
	 * @param endTime  the value for UserPay.EndTime
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime == null ? null : endTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.CrDate
	 * @return  the value of UserPay.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.CrDate
	 * @param crDate  the value for UserPay.CrDate
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.CrUser
	 * @return  the value of UserPay.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.CrUser
	 * @param crUser  the value for UserPay.CrUser
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.DateStamp
	 * @return  the value of UserPay.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public Date getDateStamp() {
		return dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.DateStamp
	 * @param dateStamp  the value for UserPay.DateStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setDateStamp(Date dateStamp) {
		this.dateStamp = dateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserPay.UserStamp
	 * @return  the value of UserPay.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public String getUserStamp() {
		return userStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserPay.UserStamp
	 * @param userStamp  the value for UserPay.UserStamp
	 * @mbggenerated  Sun May 08 19:27:55 CST 2016
	 */
	public void setUserStamp(String userStamp) {
		this.userStamp = userStamp == null ? null : userStamp.trim();
	}
}