package com.chungli.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public UserProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmailIsNull() {
            addCriterion("Email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("Email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("Email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("Email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("Email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("Email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("Email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("Email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("Email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("Email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("Email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("Email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("Email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNull() {
            addCriterion("ChineseName is null");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNotNull() {
            addCriterion("ChineseName is not null");
            return (Criteria) this;
        }

        public Criteria andChineseNameEqualTo(String value) {
            addCriterion("ChineseName =", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotEqualTo(String value) {
            addCriterion("ChineseName <>", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThan(String value) {
            addCriterion("ChineseName >", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThanOrEqualTo(String value) {
            addCriterion("ChineseName >=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThan(String value) {
            addCriterion("ChineseName <", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThanOrEqualTo(String value) {
            addCriterion("ChineseName <=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLike(String value) {
            addCriterion("ChineseName like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotLike(String value) {
            addCriterion("ChineseName not like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameIn(List<String> values) {
            addCriterion("ChineseName in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotIn(List<String> values) {
            addCriterion("ChineseName not in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameBetween(String value1, String value2) {
            addCriterion("ChineseName between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotBetween(String value1, String value2) {
            addCriterion("ChineseName not between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("Phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("Phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("Phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("Phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("Phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("Phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("Phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("Phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("Phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("Phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("Phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("Phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("Phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("Phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andTeamIsNull() {
            addCriterion("Team is null");
            return (Criteria) this;
        }

        public Criteria andTeamIsNotNull() {
            addCriterion("Team is not null");
            return (Criteria) this;
        }

        public Criteria andTeamEqualTo(Integer value) {
            addCriterion("Team =", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamNotEqualTo(Integer value) {
            addCriterion("Team <>", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamGreaterThan(Integer value) {
            addCriterion("Team >", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamGreaterThanOrEqualTo(Integer value) {
            addCriterion("Team >=", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamLessThan(Integer value) {
            addCriterion("Team <", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamLessThanOrEqualTo(Integer value) {
            addCriterion("Team <=", value, "team");
            return (Criteria) this;
        }

        public Criteria andTeamIn(List<Integer> values) {
            addCriterion("Team in", values, "team");
            return (Criteria) this;
        }

        public Criteria andTeamNotIn(List<Integer> values) {
            addCriterion("Team not in", values, "team");
            return (Criteria) this;
        }

        public Criteria andTeamBetween(Integer value1, Integer value2) {
            addCriterion("Team between", value1, value2, "team");
            return (Criteria) this;
        }

        public Criteria andTeamNotBetween(Integer value1, Integer value2) {
            addCriterion("Team not between", value1, value2, "team");
            return (Criteria) this;
        }

        public Criteria andCrDateIsNull() {
            addCriterion("CrDate is null");
            return (Criteria) this;
        }

        public Criteria andCrDateIsNotNull() {
            addCriterion("CrDate is not null");
            return (Criteria) this;
        }

        public Criteria andCrDateEqualTo(Date value) {
            addCriterion("CrDate =", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotEqualTo(Date value) {
            addCriterion("CrDate <>", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateGreaterThan(Date value) {
            addCriterion("CrDate >", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CrDate >=", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateLessThan(Date value) {
            addCriterion("CrDate <", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateLessThanOrEqualTo(Date value) {
            addCriterion("CrDate <=", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateIn(List<Date> values) {
            addCriterion("CrDate in", values, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotIn(List<Date> values) {
            addCriterion("CrDate not in", values, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateBetween(Date value1, Date value2) {
            addCriterion("CrDate between", value1, value2, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotBetween(Date value1, Date value2) {
            addCriterion("CrDate not between", value1, value2, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrUserIsNull() {
            addCriterion("CrUser is null");
            return (Criteria) this;
        }

        public Criteria andCrUserIsNotNull() {
            addCriterion("CrUser is not null");
            return (Criteria) this;
        }

        public Criteria andCrUserEqualTo(String value) {
            addCriterion("CrUser =", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotEqualTo(String value) {
            addCriterion("CrUser <>", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserGreaterThan(String value) {
            addCriterion("CrUser >", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserGreaterThanOrEqualTo(String value) {
            addCriterion("CrUser >=", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLessThan(String value) {
            addCriterion("CrUser <", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLessThanOrEqualTo(String value) {
            addCriterion("CrUser <=", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLike(String value) {
            addCriterion("CrUser like", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotLike(String value) {
            addCriterion("CrUser not like", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserIn(List<String> values) {
            addCriterion("CrUser in", values, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotIn(List<String> values) {
            addCriterion("CrUser not in", values, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserBetween(String value1, String value2) {
            addCriterion("CrUser between", value1, value2, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotBetween(String value1, String value2) {
            addCriterion("CrUser not between", value1, value2, "crUser");
            return (Criteria) this;
        }

        public Criteria andDateStampIsNull() {
            addCriterion("DateStamp is null");
            return (Criteria) this;
        }

        public Criteria andDateStampIsNotNull() {
            addCriterion("DateStamp is not null");
            return (Criteria) this;
        }

        public Criteria andDateStampEqualTo(Date value) {
            addCriterion("DateStamp =", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampNotEqualTo(Date value) {
            addCriterion("DateStamp <>", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampGreaterThan(Date value) {
            addCriterion("DateStamp >", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampGreaterThanOrEqualTo(Date value) {
            addCriterion("DateStamp >=", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampLessThan(Date value) {
            addCriterion("DateStamp <", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampLessThanOrEqualTo(Date value) {
            addCriterion("DateStamp <=", value, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampIn(List<Date> values) {
            addCriterion("DateStamp in", values, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampNotIn(List<Date> values) {
            addCriterion("DateStamp not in", values, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampBetween(Date value1, Date value2) {
            addCriterion("DateStamp between", value1, value2, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andDateStampNotBetween(Date value1, Date value2) {
            addCriterion("DateStamp not between", value1, value2, "dateStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampIsNull() {
            addCriterion("UserStamp is null");
            return (Criteria) this;
        }

        public Criteria andUserStampIsNotNull() {
            addCriterion("UserStamp is not null");
            return (Criteria) this;
        }

        public Criteria andUserStampEqualTo(String value) {
            addCriterion("UserStamp =", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampNotEqualTo(String value) {
            addCriterion("UserStamp <>", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampGreaterThan(String value) {
            addCriterion("UserStamp >", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampGreaterThanOrEqualTo(String value) {
            addCriterion("UserStamp >=", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampLessThan(String value) {
            addCriterion("UserStamp <", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampLessThanOrEqualTo(String value) {
            addCriterion("UserStamp <=", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampLike(String value) {
            addCriterion("UserStamp like", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampNotLike(String value) {
            addCriterion("UserStamp not like", value, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampIn(List<String> values) {
            addCriterion("UserStamp in", values, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampNotIn(List<String> values) {
            addCriterion("UserStamp not in", values, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampBetween(String value1, String value2) {
            addCriterion("UserStamp between", value1, value2, "userStamp");
            return (Criteria) this;
        }

        public Criteria andUserStampNotBetween(String value1, String value2) {
            addCriterion("UserStamp not between", value1, value2, "userStamp");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNull() {
            addCriterion("EnglishName is null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNotNull() {
            addCriterion("EnglishName is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameEqualTo(String value) {
            addCriterion("EnglishName =", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotEqualTo(String value) {
            addCriterion("EnglishName <>", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThan(String value) {
            addCriterion("EnglishName >", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("EnglishName >=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThan(String value) {
            addCriterion("EnglishName <", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("EnglishName <=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLike(String value) {
            addCriterion("EnglishName like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotLike(String value) {
            addCriterion("EnglishName not like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIn(List<String> values) {
            addCriterion("EnglishName in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotIn(List<String> values) {
            addCriterion("EnglishName not in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameBetween(String value1, String value2) {
            addCriterion("EnglishName between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotBetween(String value1, String value2) {
            addCriterion("EnglishName not between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailIsNull() {
            addCriterion("LeaderEmail is null");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailIsNotNull() {
            addCriterion("LeaderEmail is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailEqualTo(String value) {
            addCriterion("LeaderEmail =", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailNotEqualTo(String value) {
            addCriterion("LeaderEmail <>", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailGreaterThan(String value) {
            addCriterion("LeaderEmail >", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailGreaterThanOrEqualTo(String value) {
            addCriterion("LeaderEmail >=", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailLessThan(String value) {
            addCriterion("LeaderEmail <", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailLessThanOrEqualTo(String value) {
            addCriterion("LeaderEmail <=", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailLike(String value) {
            addCriterion("LeaderEmail like", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailNotLike(String value) {
            addCriterion("LeaderEmail not like", value, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailIn(List<String> values) {
            addCriterion("LeaderEmail in", values, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailNotIn(List<String> values) {
            addCriterion("LeaderEmail not in", values, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailBetween(String value1, String value2) {
            addCriterion("LeaderEmail between", value1, value2, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andLeaderEmailNotBetween(String value1, String value2) {
            addCriterion("LeaderEmail not between", value1, value2, "leaderEmail");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("RoleId is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("RoleId is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("RoleId =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("RoleId <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("RoleId >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("RoleId >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("RoleId <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("RoleId <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("RoleId in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("RoleId not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("RoleId between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("RoleId not between", value1, value2, "roleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UserProfile
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 17 16:11:36 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UserProfile
     *
     * @mbggenerated Sun Apr 17 16:11:36 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}